main: me.Engineer9736.TheEndProtector.Main
name: TheEndProtector
version: 0.5
author: Engineer9736
api-version: 1.16
depend: [CoreProtect]

commands:
  removedragon:
  spawndragon:
  killdragon:
  goto_end:
  goto_overworld:
  rollbacktest: